### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by Soneji** [sgoertzen/calendarpi#5]
Hi

Is docker support something you think this project would benefit from?

Thanks
Dhaval

**Comment by Soneji** [comment]
![](https://media2.giphy.com/media/ISOckXUybVfQ4/giphy.gif)

**Comment by sgoertzen** [comment]
Hey Dhaval, this project isn't supported anymore so no real need for docker with it.

Spongebob made me laugh though.  :)
